/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoratic32;

/**
 *
 * @author colegio luis ponce
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_numero1 = new javax.swing.JLabel();
        jl_numero2 = new javax.swing.JLabel();
        jl_resultado = new javax.swing.JLabel();
        jtf_numero1 = new javax.swing.JTextField();
        jtf_numero2 = new javax.swing.JTextField();
        jtf_resultado = new javax.swing.JTextField();
        jb_suma = new javax.swing.JButton();
        jb_resta = new javax.swing.JButton();
        jb_multiplicacion = new javax.swing.JButton();
        jb_division = new javax.swing.JButton();
        jb_modulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jl_numero1.setForeground(new java.awt.Color(255, 102, 153));
        jl_numero1.setText("Numero1:");

        jl_numero2.setForeground(new java.awt.Color(255, 102, 153));
        jl_numero2.setText("Numero2");

        jl_resultado.setForeground(new java.awt.Color(255, 102, 153));
        jl_resultado.setText("Resultado");

        jtf_numero1.setText("0");

        jtf_numero2.setText("0");

        jb_suma.setForeground(new java.awt.Color(255, 102, 153));
        jb_suma.setText("+");
        jb_suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_sumaMouseClicked(evt);
            }
        });

        jb_resta.setForeground(new java.awt.Color(255, 102, 153));
        jb_resta.setText("-");
        jb_resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_restaMouseClicked(evt);
            }
        });

        jb_multiplicacion.setForeground(new java.awt.Color(255, 102, 153));
        jb_multiplicacion.setText("*");
        jb_multiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_multiplicacionMouseClicked(evt);
            }
        });

        jb_division.setForeground(new java.awt.Color(255, 102, 153));
        jb_division.setText("/");
        jb_division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_divisionMouseClicked(evt);
            }
        });

        jb_modulo.setForeground(new java.awt.Color(255, 102, 153));
        jb_modulo.setText("%");
        jb_modulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_moduloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jl_numero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_numero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_suma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_resta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_multiplicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_division)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_modulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_numero1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_numero2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jtf_numero2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_resultado)
                    .addComponent(jl_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_suma)
                    .addComponent(jb_resta)
                    .addComponent(jb_multiplicacion)
                    .addComponent(jb_division)
                    .addComponent(jb_modulo))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_sumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_sumaMouseClicked
        // TODO add your handling code here:
        int numero1 = Integer.parseInt(jtf_numero1.getText());
        int numero2 = Integer.parseInt(jtf_numero2.getText());
        int resultado = numero1 + numero2;
        jtf_resultado.setText("" + resultado);
    }//GEN-LAST:event_jb_sumaMouseClicked

    private void jb_restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_restaMouseClicked
        // TODO add your handling code here:
        int numero1 = Integer.parseInt(jtf_numero1.getText());
        int numero2 = Integer.parseInt(jtf_numero2.getText());
        int resultado = numero1 - numero2;
        jtf_resultado.setText("" + resultado);
    }//GEN-LAST:event_jb_restaMouseClicked

    private void jb_multiplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_multiplicacionMouseClicked
        // TODO add your handling code here:
        int numero1 = Integer.parseInt(jtf_numero1.getText());
        int numero2 = Integer.parseInt(jtf_numero2.getText());
        int resultado = numero1 * numero2;
        jtf_resultado.setText("" + resultado);
    }//GEN-LAST:event_jb_multiplicacionMouseClicked

    private void jb_divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_divisionMouseClicked
        // TODO add your handling code here:
        int numero1 = Integer.parseInt(jtf_numero1.getText());
        int numero2 = Integer.parseInt(jtf_numero2.getText());
        int resultado = numero1 / numero2;
        jtf_resultado.setText("" + resultado);
    }//GEN-LAST:event_jb_divisionMouseClicked

    private void jb_moduloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_moduloMouseClicked
        // TODO add your handling code here:
        int numero1 = Integer.parseInt(jtf_numero1.getText());
        int numero2 = Integer.parseInt(jtf_numero2.getText());
        int resultado = numero1 % numero2;
        jtf_resultado.setText("" + resultado);
    }//GEN-LAST:event_jb_moduloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_division;
    private javax.swing.JButton jb_modulo;
    private javax.swing.JButton jb_multiplicacion;
    private javax.swing.JButton jb_resta;
    private javax.swing.JButton jb_suma;
    private javax.swing.JLabel jl_numero1;
    private javax.swing.JLabel jl_numero2;
    private javax.swing.JLabel jl_resultado;
    private javax.swing.JTextField jtf_numero1;
    private javax.swing.JTextField jtf_numero2;
    private javax.swing.JTextField jtf_resultado;
    // End of variables declaration//GEN-END:variables
}
